// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGPA_CALCULATOR.Infrastructure.Data;

#nullable disable

namespace SGPA_CALCULATOR.Migrations
{
    [DbContext(typeof(SgpaDbContext))]
    partial class SgpaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubjectMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<bool>("IsNonCreditForSgpa")
                        .HasColumnType("bit");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubjectMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BMATS101",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPHYS102",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCHES102",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 4,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPOPS103",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 5,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCEDK103",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 6,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BMATM101",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 7,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPHYM102",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 8,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCHEM102",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 9,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BEMEM103",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 10,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCEDK103",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 11,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BMATE101",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 12,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPHYE102",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 13,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BEEE103",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 14,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BEMEM103",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 15,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BBEE103",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 16,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BMATC101",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 17,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPHYC102",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 18,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCIVC103",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 19,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK104A",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 20,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK104B",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 21,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK104C",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 22,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK104D",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 23,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK104E",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 24,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105A",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 25,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105B",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 26,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105C",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 27,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105D",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 28,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105E",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 29,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105F",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 30,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105G",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 31,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105H",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 32,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105I",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 33,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105J",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 34,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPLCK105A",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 35,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPLCK105B",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 36,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPLCK105C",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 37,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPLCK105D",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 38,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCEDK109",
                            SubjectType = "Drawing"
                        },
                        new
                        {
                            Id = 39,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BKSK105",
                            SubjectType = "Language"
                        },
                        new
                        {
                            Id = 40,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BIDTK158",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 41,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BENGK106",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 42,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPWSK106",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 43,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BKSKK107",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 44,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BKBKK107",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 45,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BICOK107",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 46,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BSFH108",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 47,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BIDTK108",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 48,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BIDTK158",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 49,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BSFHK158",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 50,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BMATS201",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 51,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPHYS202",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 52,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCHES202",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 53,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCEDK203",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 54,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BMATM201",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 55,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPHYM202",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 56,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCHEM202",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 57,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BEMEM203",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 58,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCEDK203",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 59,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BEME203",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 60,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BMATE201",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 61,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPHYE202",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 62,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BEEE203",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 63,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BEMEM203",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 64,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BBEE203",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 65,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BMATC201",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 66,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPHYC202",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 67,
                            Credits = 4,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCIVC203",
                            SubjectType = "Integrated"
                        },
                        new
                        {
                            Id = 68,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK204A",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 69,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK204B",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 70,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK204C",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 71,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK204D",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 72,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BESCK204E",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 73,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK205A",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 74,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK205B",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 75,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK205C",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 76,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK205D",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 77,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK205E",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 78,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK205F",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 79,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK205G",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 80,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK205H",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 81,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK205I",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 82,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BETCK105J",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 83,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "22ETC15J",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 84,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPLCK205A",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 85,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPLCK205B",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 86,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPLCK205C",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 87,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPLCK205D",
                            SubjectType = "Theory"
                        },
                        new
                        {
                            Id = 88,
                            Credits = 3,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BCEDK209",
                            SubjectType = "Drawing"
                        },
                        new
                        {
                            Id = 89,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BKSK205",
                            SubjectType = "Language"
                        },
                        new
                        {
                            Id = 90,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BIDTK258",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 91,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BENGK206",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 92,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BPWSK206",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 93,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BKSKK207",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 94,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BKBKK207",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 95,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BICOK207",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 96,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BSFH208",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 97,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BIDTK208",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 98,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "KIDTK258",
                            SubjectType = "Workshop"
                        },
                        new
                        {
                            Id = 99,
                            Credits = 1,
                            IsNonCreditForSgpa = false,
                            Semester = 1,
                            SubjectCode = "BSFHK258",
                            SubjectType = "Workshop"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
