server {
    listen 80;
    listen [::]:80;
    server_name vtucalc.in www.vtucalc.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    server_name localhost;

    location /health-nginx {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
